service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-1

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: lambda_function.app
package:
  individually: true

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    timeout: 900

#functions:
##   theLambda:
##     name: cf-serverless-lambda
## #    handler: lambda.handler
##     handler: wsgi_handler.handler
##     description: test-lambda
##     timeout: 5 # seconds
##     memorySize: 128 # mb
##     package:
##       patterns:
##         - "!node_modules/**"
##         - "!yarn.lock"
##         - "!package-lock.json"
##         - "!package.json"
# api:
#   handler: wsgi_handler.handler
#      events:
#        - http: ANY /
#        - http: 'ANY {proxy+}'
#      timeout: 900
